// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Automatically categorizes announcements using AI to reduce manual tagging effort.
 *
 * - categorizeAnnouncement - A function that categorizes announcements.
 * - CategorizeAnnouncementInput - The input type for the categorizeAnnouncement function.
 * - CategorizeAnnouncementOutput - The return type for the categorizeAnnouncement function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const CategorizeAnnouncementInputSchema = z.object({
  title: z.string().describe('The title of the announcement.'),
  description: z.string().describe('The description of the announcement.'),
});
export type CategorizeAnnouncementInput = z.infer<typeof CategorizeAnnouncementInputSchema>;

const CategorizeAnnouncementOutputSchema = z.object({
  categories: z.array(z.string()).describe('The categories the announcement belongs to.'),
});
export type CategorizeAnnouncementOutput = z.infer<typeof CategorizeAnnouncementOutputSchema>;

export async function categorizeAnnouncement(input: CategorizeAnnouncementInput): Promise<CategorizeAnnouncementOutput> {
  return categorizeAnnouncementFlow(input);
}

const categorizeAnnouncementPrompt = ai.definePrompt({
  name: 'categorizeAnnouncementPrompt',
  input: {
    schema: z.object({
      title: z.string().describe('The title of the announcement.'),
      description: z.string().describe('The description of the announcement.'),
    }),
  },
  output: {
    schema: z.object({
      categories: z.array(z.string()).describe('The categories the announcement belongs to.'),
    }),
  },
  prompt: `You are an expert in categorizing announcements.

  Given the title and description of an announcement, you will determine the categories it belongs to.
  The categories should be relevant and specific to the announcement.

  Title: {{{title}}}
  Description: {{{description}}}

  Categories:`, // Ensure the response is formatted as a JSON array of strings
});

const categorizeAnnouncementFlow = ai.defineFlow<
  typeof CategorizeAnnouncementInputSchema,
  typeof CategorizeAnnouncementOutputSchema
>({
  name: 'categorizeAnnouncementFlow',
  inputSchema: CategorizeAnnouncementInputSchema,
  outputSchema: CategorizeAnnouncementOutputSchema,
},
async input => {
  const {output} = await categorizeAnnouncementPrompt(input);
  return output!;
});
